            - name: Autify for Mobile Run Test Plan
  # You may pin to the exact commit or the version.
  # uses: autifyhq/mobile-run-test-plan-action@40bebde5f60117ec81312051028d22238649d280
  uses: autifyhq/mobile-run-test-plan-action@v1.0.0
  with:
    # Personal Access Token
    autify_for_mobile_api_token: 
    # Test Plan ID that you want to run
    test_plan_id: 
    # Build ID that you want to use
    build_id: 
    # Test Plan API base URL
    test_plan_api_base_url: https://mobile-app.autify.com/api/v1/test_plans/
          
